spring:
  datasource:
    name: datasource
    initialize: true
    url: jdbc:mysql://10.95.120.55:3336/littleboyonlinetest?characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useDynamicCharsetInfo=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    max-active: 60
    max-idle: 10
    min-idle: 10
    initial-size: 30
    validation-query: select 1
    test-on-borrow: true
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 3000
    min-evictable-idle-time-millis: 3000
    max-wait: 3000
    jmx-enabled: true

  cache:
    cache-names: groupInfo
    guava:
      spec:
        maximumSize: 300
        expireAfterWrite: 3600
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false


server:
  port: 8080
  tomcat:
    max-threads: 200
    accesslog:
      enabled: true
      directory: "/Users/mac/Documents/demo@workspace/demo/logs/manhattan/manhattan-demo"
      pattern: '%{X-Forwarded-For}i %h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %D'
      rotatable: true
      prefix: "access-log"
      suffix: ".log"


mybatis:
  typeAliasesPackage: com.example.didi.domain.*
  mapperLocations: classpath:mapper/*.xml


